version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "49222:80"
    container_name: wxcloud_my-video-service
    labels:
      - wxPort=27082
      - hostPort=49222
      - wxcloud=my-video-service
      - role=container
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=lql@4518
      - MYSQL_ADDRESS=10.27.100.116:3306
networks:
  default:
    external:
      name: wxcb0
